### PR TITLE
button hover effect added

### PR DESCRIPTION
**Pull request by rsrkpatwari1234**
Added a hover effect to button color.Making it more prominent when the mouse pointer is over it.
Solving issue #9

### CODE REVIEW

**Comment by rsrkpatwari1234** [comment]
@PragatiVerma18 can you please review my PR?

**Comment by rsrkpatwari1234** [comment]
@PragatiVerma18 please review my PR.It is about the end of NWOC.Please review the Pr

**Review by PragatiVerma18 — APPROVED** [review]
Looks good to me! Thanks @rsrkpatwari1234

**Comment by rsrkpatwari1234** [comment]
Also @PragatiVerma18, please review this issue #26 as well and update my update my score for the pr and issue(if approved)

**Pull request merged**
